=== PersonalCastro/PracticasLM-Xml/PracticasLM_Xml/Practicas_1.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="criminales">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="criminal" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:group ref="info_persona"/>
            </xs:sequence>
            <xs:attributeGroup ref="info_atributos"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:attributeGroup name="info_atributos">
    <xs:attribute name="dni" type="tipo_dni" use="required"/>
    <xs:attribute name="sexo" type="tipo_sexo" use="required"/>
  </xs:attributeGroup>

  <xs:simpleType name="tipo_dni">
    <xs:restriction base="xs:string">
      <xs:pattern value="\d{7}-[1-9]-[A-Z]"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="tipo_sexo">
    <xs:restriction base="xs:string">
      <xs:enumeration value="H"/>
      <xs:enumeration value="M"/>
    </xs:restriction>
  </xs:simpleType>


  <xs:group name="info_persona">
    <xs:sequence>

      <xs:element name="nombre">
        <xs:simpleType>
          <xs:restriction base="xs:string">
              <xs:pattern value="[A-Za-zÀ-ÿ]{1,24},[A-Za-zÀ-ÿ]{1,75}"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>

      <xs:element name="fecha_nacimiento">
        <xs:simpleType>
          <xs:restriction base="xs:string">
              <xs:pattern value="[0-3][0-9]/[0-1][0-9]/[1-2][0-9]{3}"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>

      <xs:element name="altura">
        <xs:simpleType>
          <xs:restriction base="xs:string">
              <xs:pattern value="[0-2][0-9]{2} cm."/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>

      <xs:element name="descripcion_fisica">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="200"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>

      <xs:element name="direccion_completa">
        <xs:complexType>
          <xs:sequence>
            <xs:group ref="grupo_direccion"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>

      <xs:group ref="carcel_libertad" minOccurs="0"/>

      <xs:element name="lista_delitos" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="200"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>

      <xs:element name="juzgado" minOccurs="0">
        <xs:complexType>
          <xs:element name="pena" type="xs:string">
            <xs:complexType>
              <xs:attribute name="estado" type="cumpliendo_finalizada"/>
            </xs:complexType>
          </xs:element>
        </xs:complexType>
      </xs:element>

    </xs:sequence>
  </xs:group>

  <xs:group name="grupo_direccion">
    <xs:sequence>

      <xs:element name="direccion">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="120"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>

      <xs:element name="localidad" type="tipo_loc_prov"/>

      <xs:element name="codigo_postal">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:pattern value="\d{5}"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>

      <xs:element name="provincia" type="tipo_loc_prov"/>

    </xs:sequence>
  </xs:group>

  <xs:group name="carcel_libertad">
    <xs:choice>
      <xs:element name="libertad"/>
      <xs:element name="carcel"/>
    </xs:choice>
  </xs:group>

  <xs:simpleType name="cumpliendo_finalizada">
    <xs:restriction base="xs:string">
      <xs:enumeration value="cumpliendo"/>
      <xs:enumeration value="finalizada"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="tipo_loc_prov">
    <xs:restriction base="xs:string">
      <xs:maxLength value="80"/>
    </xs:restriction>
  </xs:simpleType>

</xs:schema>

=== PersonalCastro/PracticasLM-Xml/PracticasLM_Xml/Precticas_1.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE criminales [
<!ELEMENT criminales (criminal)*>
<!ELEMENT criminal (nombre, fecha_nacimiento, altura, descripcion_fisica, historial_medico? ,direccion_completa, (libertad | carcel)?, lista_delitos?, juzgado?) >
<!ATTLIST criminal dni ID #REQUIRED>
<!ATTLIST criminal sexo CDATA #FIXED "H|M">
  <!ELEMENT nombre (#PCDATA)>
  <!ELEMENT fecha_nacimiento (#PCDATA)>
  <!ELEMENT altura (#PCDATA)>
  <!ELEMENT descripcion_fisica (#PCDATA)>
  <!ELEMENT direccion_completa (direccion, localidad, codigo_postal, provincia)>
    <!ELEMENT direccion (#PCDATA)>
    <!ELEMENT localidad (#PCDATA)>
    <!ELEMENT codigo_postal (#PCDATA)>
    <!ELEMENT provincia (#PCDATA)>
  <!ELEMENT historial_medico (#PCDATA)>
  <!ELEMENT libertad EMPTY>
  <!ELEMENT carcel EMPTY>
  <!ELEMENT lista_delitos (#PCDATA)>
  <!ELEMENT juzgado (pena?)>
    <!ELEMENT pena (#PCDATA)>
    <!ATTLIST pena estado CDATA #FIXED "cumpliendo | finalizada">
]>
<criminales xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Practicas_1.xsd">

  <criminal dni="76591628H" sexo="H">
    <nombre> Castro Salazar, Pablo </nombre>
    <fecha_nacimiento> 18/09/2000 </fecha_nacimiento>
    <altura> 180 cm.</altura>
    <descripcion_fisica> Su color de pelo es castaño y tiene los ojos verdes </descripcion_fisica>
    <direccion_completa>
      <direccion> Cristobal de morales n.34 </direccion>
      <localidad> Granada </localidad>
      <codigo_postal> 18013 </codigo_postal>
      <provincia> Granada </provincia>
    </direccion_completa>
    <libertad/>
  </criminal>

  <criminal dni="97235678F" sexo="M">
    <nombre> Muñoz Gutierrez , Alejandro </nombre>
    <fecha_nacimiento> 05/05/2000 </fecha_nacimiento>
    <altura> 170 cm.</altura>
    <descripcion_fisica> Su color de pelo es pelirrojo y tiene los ojos marrones </descripcion_fisica>
    <direccion_completa>
      <direccion> Los rosales n.6 </direccion>
      <localidad> Jun </localidad>
      <codigo_postal> 18213 </codigo_postal>
      <provincia> Granada </provincia>
    </direccion_completa>
    <historial_medico>
          Transtorno mental cronico: Esquizofrenia
    </historial_medico>
    <libertad/>
    <lista_delitos>
      1. Poner piña a la Pizza
    </lista_delitos>
    <juzgado>
      <pena estado="finalizada"> Servicios comunitarios </pena>
    </juzgado>
  </criminal>

  <criminal dni="15516959D" sexo="M">
    <nombre> Ortega Bastida , David </nombre>
    <fecha_nacimiento> 21/09/1998 </fecha_nacimiento>
    <altura> 175 cm.</altura>
    <descripcion_fisica> Su color de pelo es rubio y tiene los ojos verdes </descripcion_fisica>
    <direccion_completa>
      <direccion> Olivo n.8 </direccion>
      <localidad> Armilla </localidad>
      <codigo_postal> 18513 </codigo_postal>
      <provincia> Granada </provincia>
    </direccion_completa>
    <carcel/>
    <lista_delitos>
      1. feat con Pitbull
    </lista_delitos>
    <juzgado>
      <pena estado="cumpliendo"> Cadena perpetua </pena>
    </juzgado>
  </criminal>

</criminales>
